import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ChangeEvent,
  type KeyboardEvent,
} from "react";
import styles from "./ScoutApplyFlowScreen.module.css";

/**
 * ВЕТКА: pl/scout-apply-flow-radar
 * Прототип сквозного флоу AIHR-530:
 * Public Request Landing → Account (sign-up + verify) → Screening (single chat:
 * pre-filled role/goal → CV upload → AI extracts profile → AI drafts cover letter
 * → user accepts) → Confirmation (final preview) → Radar (Project Details, Applied).
 *
 * Стиль: строго ч/б (см. setup-checklist).
 * Скрининг — один непрерывный чат с фазами, а не отдельные snapshot-окна.
 * Все навигационные действия идут через PrototypeBar (черная панель сверху).
 */

type StepId = "landing" | "register" | "screening" | "confirm" | "radar";

const STEPS: { id: StepId; name: string }[] = [
  { id: "landing", name: "1. Public Request Landing" },
  { id: "register", name: "2. Account — sign-up + verify" },
  { id: "screening", name: "3. Screening (chat: CV → profile → cover letter)" },
  { id: "confirm", name: "4. Final review" },
  { id: "radar", name: "5. Radar — Project Details (Applied)" },
];

const REQUEST_TITLE = "Graphic Designer for Social Media Visuals";
const COMPANY = "Studio M";
const COMPANY_LOC = "United Arab Emirates";
const COMPANY_TZ = "GMT+4";

/* Snapshot defaults so the prototype stays demo-able end-to-end. */
const SAMPLE_USER = {
  firstName: "Jessica",
  lastName: "Martinez",
  email: "jessica.martinez@gmail.com",
};

const EXTRACTED = {
  profession: "Graphic Designer",
  level: "Middle · 2–5 years",
  skills: ["Figma", "Adobe Photoshop", "Illustrator", "Canva"],
  location: "Lisbon, Portugal",
  rate: "$30/hr",
  languages: ["English — Fluent", "Spanish — Conversational"],
};

/**
 * Sample cover letter / extras — only used by the "Use sample materials"
 * helper button in the prototype, NOT auto-generated by AI.
 */
const SAMPLE_COVER = `Hi Studio M team,

Your brief jumped out for me — I've shipped social-media systems for three D2C brands in the last 18 months, and the focus on scaling visuals across channels is exactly where I do my best work.

A few things from my CV that should map well:
• Figma + Photoshop + Illustrator daily, Canva for hand-off to non-designers
• Built and maintained brand kits, Instagram and TikTok templates
• Comfortable working independently, English and Spanish

Happy to walk through the most relevant pieces of my portfolio whenever it suits you.

— Jessica Martinez`;

const SAMPLE_EXTRAS = ["Jessica_Martinez_Portfolio_2026.pdf"];

const SAMPLE_LINKS = {
  linkedin: "linkedin.com/in/jessicamartinez",
  portfolio: "behance.net/jessicamartinez",
};

/* ----------------- helpers ----------------- */

function useStep() {
  const [step, setStep] = useState<StepId>(() => {
    const hash = (typeof window !== "undefined" && window.location.hash.replace("#", "")) as StepId;
    return STEPS.find((s) => s.id === hash) ? hash : "landing";
  });

  useEffect(() => {
    if (typeof window !== "undefined") window.location.hash = step;
  }, [step]);

  const idx = STEPS.findIndex((s) => s.id === step);
  const goNext = useCallback(() => {
    if (idx < STEPS.length - 1) setStep(STEPS[idx + 1].id);
  }, [idx]);
  const goBack = useCallback(() => {
    if (idx > 0) setStep(STEPS[idx - 1].id);
  }, [idx]);

  return { step, setStep, idx, goNext, goBack };
}

/* ============================================================
   Top prototype bar — навигатор по шагам прототипа
   ============================================================ */

function PrototypeBar({
  step,
  idx,
  goNext,
  goBack,
  jump,
}: {
  step: StepId;
  idx: number;
  goNext: () => void;
  goBack: () => void;
  jump: (id: StepId) => void;
}) {
  return (
    <div className={styles.protoBar}>
      <div className={styles.protoLeft}>
        <button
          type="button"
          className={`${styles.protoBtn} ${styles.protoBtnGhost}`}
          onClick={goBack}
          disabled={idx === 0}
        >
          ← Back
        </button>
        <span className={styles.protoStepIndex}>
          Step {idx + 1} / {STEPS.length}
        </span>
        <span className={styles.protoStepName}>{STEPS[idx].name}</span>
      </div>
      <div className={styles.protoRight}>
        <select
          aria-label="Jump to step"
          value={step}
          onChange={(e) => jump(e.target.value as StepId)}
          className={styles.protoBtn}
        >
          {STEPS.map((s) => (
            <option key={s.id} value={s.id}>
              {s.name}
            </option>
          ))}
        </select>
        <button
          type="button"
          className={styles.protoBtn}
          onClick={goNext}
          disabled={idx === STEPS.length - 1}
        >
          Next →
        </button>
      </div>
    </div>
  );
}

/* ============================================================
   1) LANDING
   ============================================================ */

function LandingStep({ goNext }: { goNext: () => void }) {
  return (
    <div className={styles.frame}>
      <div className={styles.appHeader}>
        <div className={styles.appLogo}>Mellow Scout</div>
        <div className={styles.appHeaderRight}>
          <span>EN</span>
          <span>Sign in</span>
        </div>
      </div>

      <div className={styles.landingBody}>
        <div className={styles.landingMain}>
          <div className={styles.landingPad}>
            <div className={styles.companyLine}>
              <span>{COMPANY}</span>
              <span className={styles.dot}>·</span>
              <span>{COMPANY_LOC}</span>
              <span className={styles.dot}>·</span>
              <span>{COMPANY_TZ}</span>
            </div>

            <h1 className={styles.requestTitle}>{REQUEST_TITLE}</h1>
            <p className={styles.requestDescription}>
              We are seeking a talented Graphic Designer to revitalize our social media visuals
              and marketing materials. The goal: enhance brand identity, deliver visuals that
              engage, and ship work that scales across channels.
            </p>

            <div className={styles.metaBlock}>
              <p className={styles.metaLabel}>Experience level</p>
              <div className={styles.pillRow}>
                <span className={styles.pill}>Middle</span>
              </div>
            </div>

            <div className={styles.metaBlock}>
              <p className={styles.metaLabel}>Skills and tech</p>
              <div className={styles.pillRow}>
                <span className={styles.pill}>Figma</span>
                <span className={styles.pill}>Canva</span>
                <span className={styles.pill}>Adobe Photoshop</span>
                <span className={styles.pill}>Logo Design</span>
              </div>
            </div>

            <div className={styles.metaBlock}>
              <p className={styles.metaLabel}>Languages required</p>
              <div className={styles.pillRow}>
                <span className={styles.pill}>English</span>
                <span className={styles.pill}>Spanish</span>
              </div>
            </div>

            <div className={styles.section}>
              <h2 className={styles.sectionTitle}>Key responsibilities</h2>
              <p className={styles.sectionText}>
                Design and deliver high-quality visual content for social media. Create graphics,
                illustrations, and layouts aligned with brand guidelines. Collaborate with the
                marketing team on creative concepts and campaign visuals.
              </p>
            </div>

            <div className={styles.section}>
              <h2 className={styles.sectionTitle}>Requirements</h2>
              <p className={styles.sectionText}>
                Proficiency in Figma, Adobe Creative Suite, and Canva. Strong portfolio
                demonstrating creative design skills. Independent execution and attention to
                detail. Excellent written communication.
              </p>
            </div>

            <div className={styles.applyCard}>
              <h3 className={styles.applyTitle}>Ready to apply?</h3>
              <p className={styles.applySub}>
                Create a quick account, then upload your CV — we'll pre-fill everything so you
                only review and submit.
              </p>

              <button type="button" className={styles.primaryBtn} onClick={goNext}>
                Apply now
              </button>
              <div style={{ textAlign: "center", marginTop: 12 }}>
                <button type="button" className={styles.linkBtn} onClick={goNext}>
                  Already have an account? Sign in →
                </button>
              </div>
            </div>
          </div>
        </div>

        <aside className={styles.sidebar}>
          <div className={styles.sidebarRow}>
            <span className={styles.sidebarKey}>Hourly rate</span>
            <span>$25–35/hr</span>
          </div>
          <div className={styles.sidebarRow}>
            <span className={styles.sidebarKey}>Workload</span>
            <span>Under 20 hrs/week</span>
          </div>
          <div className={styles.sidebarRow}>
            <span className={styles.sidebarKey}>Project type</span>
            <span>Ongoing</span>
          </div>
          <div className={styles.sidebarRow}>
            <span className={styles.sidebarKey}>Posted</span>
            <span>3 days ago</span>
          </div>
          <div className={styles.sidebarRow}>
            <span className={styles.sidebarKey}>Expires in</span>
            <span>11 days</span>
          </div>
          <div className={styles.sidebarRow}>
            <span className={styles.sidebarKey}>Viewed · Applied</span>
            <span>342 · 12</span>
          </div>
        </aside>
      </div>
    </div>
  );
}

/* ============================================================
   2) REGISTER — sign-up form → email-code verification
   Per Figma: рега-форма (First name + Last name + Email) →
   "Check your email" с 6-значным кодом → дальше в screening.
   ============================================================ */

type RegPhase = "form" | "verify";

function RegistrationStep({
  firstName,
  lastName,
  email,
  setFirstName,
  setLastName,
  setEmail,
  goNext,
}: {
  firstName: string;
  lastName: string;
  email: string;
  setFirstName: (v: string) => void;
  setLastName: (v: string) => void;
  setEmail: (v: string) => void;
  goNext: () => void;
}) {
  const [phase, setPhase] = useState<RegPhase>("form");
  const [code, setCode] = useState<string[]>(["", "", "", "", "", ""]);
  const codeRefs = useRef<Array<HTMLInputElement | null>>([]);

  const canContinueForm = firstName.trim() && lastName.trim() && /\S+@\S+\.\S+/.test(email);
  const canVerify = code.every((c) => c !== "");

  const handleCodeChange = (i: number, v: string) => {
    const digit = v.replace(/\D/g, "").slice(-1);
    setCode((prev) => {
      const next = [...prev];
      next[i] = digit;
      return next;
    });
    if (digit && i < 5) codeRefs.current[i + 1]?.focus();
  };

  const handleCodeKey = (i: number, e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !code[i] && i > 0) codeRefs.current[i - 1]?.focus();
  };

  const fillSampleCode = () => {
    const sample = ["4", "8", "2", "9", "1", "7"];
    setCode(sample);
    codeRefs.current[5]?.focus();
  };

  return (
    <div className={styles.frame}>
      <div className={styles.appHeader}>
        <div className={styles.appLogo}>Mellow</div>
        <div className={styles.appHeaderRight}>
          <span>Already have an account?</span>
          <button type="button" className={styles.linkBtn}>
            Sign in
          </button>
        </div>
      </div>

      <div className={styles.contextStrip}>
        <span className={styles.contextStripLabel}>Applying to</span>
        <span className={styles.contextStripTitle}>{REQUEST_TITLE}</span>
        <span className={styles.dot}>·</span>
        <span>{COMPANY}</span>
      </div>

      <div className={styles.regWrap}>
        <div className={styles.regCard}>
          {phase === "form" ? (
            <>
              <h1 className={styles.regTitle}>Create your Mellow account</h1>
              <p className={styles.regSub}>
                One account for applications, status updates, and matched projects in Radar.
              </p>

              <div className={styles.regGrid2}>
                <label className={styles.regField}>
                  <span className={styles.regLabel}>First name</span>
                  <input
                    type="text"
                    className={styles.regInput}
                    value={firstName}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => setFirstName(e.target.value)}
                    placeholder="Jessica"
                    autoComplete="given-name"
                  />
                </label>
                <label className={styles.regField}>
                  <span className={styles.regLabel}>Last name</span>
                  <input
                    type="text"
                    className={styles.regInput}
                    value={lastName}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => setLastName(e.target.value)}
                    placeholder="Martinez"
                    autoComplete="family-name"
                  />
                </label>
              </div>

              <label className={styles.regField}>
                <span className={styles.regLabel}>Email</span>
                <input
                  type="email"
                  className={styles.regInput}
                  value={email}
                  onChange={(e: ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}
                  placeholder="you@email.com"
                  autoComplete="email"
                />
                <span className={styles.regHint}>We'll send a 6-digit code to verify it's you.</span>
              </label>

              <button
                type="button"
                className={styles.primaryBtn}
                onClick={() => setPhase("verify")}
                disabled={!canContinueForm}
              >
                Continue →
              </button>

              <p className={styles.regFooter}>
                By continuing you agree to Mellow's <a href="#landing">Terms</a> and{" "}
                <a href="#landing">Privacy</a>.
              </p>
            </>
          ) : (
            <>
              <button
                type="button"
                className={styles.regBack}
                onClick={() => setPhase("form")}
              >
                ← Edit email
              </button>
              <h1 className={styles.regTitle}>Check your email</h1>
              <p className={styles.regSub}>
                We sent a 6-digit code to <strong>{email}</strong>. It expires in 10 minutes.
              </p>

              <div className={styles.codeRow}>
                {code.map((c, i) => (
                  <input
                    key={i}
                    ref={(el) => {
                      codeRefs.current[i] = el;
                    }}
                    type="text"
                    inputMode="numeric"
                    maxLength={1}
                    value={c}
                    onChange={(e) => handleCodeChange(i, e.target.value)}
                    onKeyDown={(e) => handleCodeKey(i, e)}
                    className={styles.codeInput}
                    aria-label={`Digit ${i + 1}`}
                  />
                ))}
              </div>

              <button
                type="button"
                className={styles.primaryBtn}
                onClick={goNext}
                disabled={!canVerify}
              >
                Verify & continue →
              </button>

              <div className={styles.regAltRow}>
                <button type="button" className={styles.linkBtn} onClick={fillSampleCode}>
                  Use sample code (prototype)
                </button>
                <button type="button" className={styles.linkBtn}>
                  Resend code
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

/* ============================================================
   3) SCREENING — single continuous chat
   Pre-filled bubbles for Role + Goal, then AI asks for CV,
   user uploads sample, AI shows extracted profile summary,
   user confirms, AI drafts a cover letter, user accepts,
   then continues to final review.
   ============================================================ */

type ChatPhase = "askCv" | "thinkingCv" | "showSummary" | "writeCover" | "ready";

function ScreeningStep({
  firstName,
  lastName,
  email,
  cover,
  setCover,
  extras,
  setExtras,
  links,
  setLinks,
  goNext,
}: {
  firstName: string;
  lastName: string;
  email: string;
  cover: string;
  setCover: (v: string) => void;
  extras: string[];
  setExtras: (v: string[]) => void;
  links: ApplicationLinks;
  setLinks: (v: ApplicationLinks) => void;
  goNext: () => void;
}) {
  const [phase, setPhase] = useState<ChatPhase>("askCv");
  const endRef = useRef<HTMLDivElement | null>(null);
  const fullName = `${firstName || "Jessica"} ${lastName || "Martinez"}`.trim();
  const safeEmail = email || SAMPLE_USER.email;

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
  }, [phase]);

  const handleUploadCv = () => {
    setPhase("thinkingCv");
    window.setTimeout(() => setPhase("showSummary"), 1100);
  };

  const handleConfirmSummary = () => setPhase("writeCover");

  const handleAcceptCover = () => setPhase("ready");

  const handleAddSampleExtra = () => {
    if (!extras.includes(SAMPLE_EXTRAS[0])) {
      setExtras([...extras, ...SAMPLE_EXTRAS]);
    }
  };

  const handleRemoveExtra = (file: string) => {
    setExtras(extras.filter((f) => f !== file));
  };

  const handleUseSampleMaterials = () => {
    setCover(SAMPLE_COVER);
    if (!extras.includes(SAMPLE_EXTRAS[0])) {
      setExtras([...extras, ...SAMPLE_EXTRAS]);
    }
    setLinks({ ...SAMPLE_LINKS });
  };

  const coverReady = cover.trim().length > 0;

  const showCvUser = phase !== "askCv";
  const showThinkingCv = phase === "thinkingCv";
  const showSummary =
    phase === "showSummary" || phase === "writeCover" || phase === "ready";
  const showWriteCover = phase === "writeCover" || phase === "ready";
  const showReady = phase === "ready";

  return (
    <div className={styles.screeningWrap}>
      <div className={styles.screeningHeader}>
        <div className={styles.appLogo}>Mellow</div>
        <div className={styles.screeningHeaderRight}>
          <span>{safeEmail}</span>
        </div>
      </div>

      <div className={styles.contextStrip}>
        <span className={styles.contextStripLabel}>Applying to</span>
        <span className={styles.contextStripTitle}>{REQUEST_TITLE}</span>
        <span className={styles.dot}>·</span>
        <span>{COMPANY}</span>
      </div>

      <div className={styles.chatArea}>
        <div className={styles.chatInner}>
          {/* --- Compact request summary at top of chat --- */}
          <div className={styles.requestRecap}>
            <div className={styles.requestRecapHead}>
              <span className={styles.requestRecapKicker}>You're applying to</span>
              <h2 className={styles.requestRecapTitle}>{REQUEST_TITLE}</h2>
              <div className={styles.requestRecapSub}>
                {COMPANY} · {COMPANY_LOC}
              </div>
            </div>
            <div className={styles.requestRecapMetrics}>
              <div className={styles.recapMetric}>
                <span className={styles.recapLabel}>Budget</span>
                <span className={styles.recapValueLg}>$25–35/hr</span>
              </div>
              <div className={styles.recapMetric}>
                <span className={styles.recapLabel}>Project type</span>
                <span className={styles.recapValue}>Ongoing</span>
              </div>
              <div className={styles.recapMetric}>
                <span className={styles.recapLabel}>Workload</span>
                <span className={styles.recapValue}>Under 20 hrs/week</span>
              </div>
            </div>
          </div>

          {/* --- Single AI greeting that recaps role/goal in one line --- */}
          <BubbleAi
            text={`Hi ${firstName || "Jessica"} — you're applying as a contractor to this request. Drop your CV and I'll pre-fill the rest, you only review and submit.`}
          />

          <div className={styles.cvUploadRow}>
            <div className={styles.cvUploadCard}>
              <div className={styles.cvUploadIcon}>↑</div>
              <div>
                <div className={styles.cvUploadTitle}>Drop your CV here</div>
                <div className={styles.cvUploadSub}>PDF, DOCX · up to 10MB</div>
              </div>
              <button
                type="button"
                className={styles.secondaryBtn}
                onClick={handleUploadCv}
                disabled={phase !== "askCv"}
              >
                {phase === "askCv" ? "Use sample CV" : "Uploaded"}
              </button>
            </div>
          </div>

          {showCvUser ? (
            <BubbleUser text={`📄 ${fullName.replace(/\s+/g, "_")}_CV.pdf · 248 KB`} />
          ) : null}

          {showThinkingCv ? <ThinkingBubble label="Reading your CV…" /> : null}

          {showSummary ? (
            <>
              <BubbleAi text="Got it. Here's what I pulled from your CV — does this look right?" />
              <div className={styles.summaryCard}>
                <SummaryRow label="Profession" value={EXTRACTED.profession} />
                <SummaryRow label="Level" value={EXTRACTED.level} />
                <SummaryRow
                  label="Top skills"
                  value={
                    <div className={styles.pillRow}>
                      {EXTRACTED.skills.map((s) => (
                        <span key={s} className={styles.pill}>
                          {s}
                        </span>
                      ))}
                    </div>
                  }
                />
                <SummaryRow label="Location" value={EXTRACTED.location} />
                <SummaryRow label="Expected rate" value={EXTRACTED.rate} />
                <SummaryRow
                  label="Languages"
                  value={
                    <div className={styles.pillRow}>
                      {EXTRACTED.languages.map((l) => (
                        <span key={l} className={styles.pill}>
                          {l}
                        </span>
                      ))}
                    </div>
                  }
                />
              </div>
              <div className={styles.chatActionRow}>
                <button
                  type="button"
                  className={styles.secondaryBtn}
                  disabled={phase !== "showSummary"}
                >
                  Edit
                </button>
                <button
                  type="button"
                  className={styles.primaryInlineBtn}
                  onClick={handleConfirmSummary}
                  disabled={phase !== "showSummary"}
                >
                  Looks right →
                </button>
              </div>
              {phase !== "showSummary" ? (
                <BubbleUser text="Looks right" />
              ) : null}
            </>
          ) : null}

          {showWriteCover ? (
            <>
              <BubbleAi text="Last step before review — write a short cover letter to Studio M, in your own words. If it helps, attach a portfolio file or drop a link." />

              <div className={styles.coverFormCard}>
                <div className={styles.coverFormHeader}>
                  <span className={styles.coverFormLabel}>Cover letter</span>
                  <button
                    type="button"
                    className={styles.linkBtn}
                    onClick={handleUseSampleMaterials}
                    disabled={phase !== "writeCover"}
                  >
                    Use sample materials (prototype)
                  </button>
                </div>
                <textarea
                  className={styles.coverChatTextarea}
                  value={cover}
                  onChange={(e) => setCover(e.target.value)}
                  placeholder={
                    "Hi Studio M team,\n\nWhy this brief feels like a fit and a few things from my background that map to it…"
                  }
                  rows={8}
                  readOnly={phase !== "writeCover"}
                />
                <div className={styles.coverFormHint}>
                  2–4 short paragraphs is usually enough. Keep it specific to this request.
                </div>

                <div className={styles.coverFormDivider} />

                <span className={styles.coverFormLabel}>Attach files (optional)</span>
                <div className={styles.extrasList}>
                  {extras.length === 0 ? (
                    <div className={styles.extrasEmpty}>
                      No files attached yet — portfolio, references, or anything else.
                    </div>
                  ) : (
                    extras.map((f) => (
                      <div key={f} className={styles.extraRow}>
                        <span className={styles.extraIcon} aria-hidden>
                          ▢
                        </span>
                        <span className={styles.extraName}>{f}</span>
                        <button
                          type="button"
                          className={styles.extraRemove}
                          onClick={() => handleRemoveExtra(f)}
                          aria-label={`Remove ${f}`}
                          disabled={phase !== "writeCover"}
                        >
                          ×
                        </button>
                      </div>
                    ))
                  )}
                </div>
                <button
                  type="button"
                  className={styles.extraAddBtn}
                  onClick={handleAddSampleExtra}
                  disabled={phase !== "writeCover"}
                >
                  + Add file (sample portfolio)
                </button>

                <div className={styles.coverFormDivider} />

                <span className={styles.coverFormLabel}>Links (optional)</span>
                <div className={styles.linksGrid}>
                  <label className={styles.linkField}>
                    <span className={styles.linkLabel}>LinkedIn</span>
                    <input
                      type="text"
                      className={styles.linkInput}
                      value={links.linkedin}
                      onChange={(e) => setLinks({ ...links, linkedin: e.target.value })}
                      placeholder="linkedin.com/in/your-handle"
                      readOnly={phase !== "writeCover"}
                    />
                  </label>
                  <label className={styles.linkField}>
                    <span className={styles.linkLabel}>Portfolio / website</span>
                    <input
                      type="text"
                      className={styles.linkInput}
                      value={links.portfolio}
                      onChange={(e) => setLinks({ ...links, portfolio: e.target.value })}
                      placeholder="behance.net/you · your-domain.com"
                      readOnly={phase !== "writeCover"}
                    />
                  </label>
                </div>
              </div>

              <div className={styles.chatActionRow}>
                <button
                  type="button"
                  className={styles.primaryInlineBtn}
                  onClick={handleAcceptCover}
                  disabled={phase !== "writeCover" || !coverReady}
                >
                  Looks good →
                </button>
              </div>
              {showReady ? (
                <BubbleUser text="Cover letter and extras attached" />
              ) : null}
            </>
          ) : null}

          {showReady ? (
            <>
              <BubbleAi text="All set. Next up — a quick preview of exactly what the client will see, then submit." />
              <div className={styles.chatActionRow}>
                <button
                  type="button"
                  className={styles.primaryInlineBtn}
                  onClick={goNext}
                >
                  Continue to review →
                </button>
              </div>
            </>
          ) : null}

          <div ref={endRef} />
        </div>

        <div className={styles.chatInput}>
          <input
            type="text"
            className={styles.chatInputField}
            placeholder="Type a message…"
            readOnly
          />
          <button type="button" className={styles.sendBtn} aria-label="Send">
            ↑
          </button>
        </div>
      </div>
    </div>
  );
}

/* --- chat micro-components --- */

function BubbleAi({ text }: { text: string }) {
  return (
    <div className={styles.bubbleRow}>
      <span className={styles.avatar}>AI</span>
      <div className={`${styles.bubble} ${styles.bubbleAi}`}>{text}</div>
    </div>
  );
}

function BubbleUser({ text }: { text: string }) {
  return (
    <div className={`${styles.bubbleRow} ${styles.bubbleRowEnd}`}>
      <div className={`${styles.bubble} ${styles.bubbleUser}`}>{text}</div>
    </div>
  );
}

function ThinkingBubble({ label }: { label: string }) {
  return (
    <div className={styles.bubbleRow}>
      <span className={styles.avatar}>AI</span>
      <div className={`${styles.bubble} ${styles.bubbleAi} ${styles.bubbleThinking}`}>
        <span className={styles.thinkingDots} aria-hidden>
          <span /> <span /> <span />
        </span>
        <span className={styles.thinkingLabel}>{label}</span>
      </div>
    </div>
  );
}

function SummaryRow({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className={styles.summaryRow}>
      <div className={styles.summaryLabel}>{label}</div>
      <div className={styles.summaryValue}>{value}</div>
    </div>
  );
}

/* ============================================================
   4) CONFIRMATION — final preview before submit
   ============================================================ */

function ConfirmStep({
  cover,
  setCover,
  extras,
  links,
  goBack,
  goNext,
}: {
  cover: string;
  setCover: (v: string) => void;
  extras: string[];
  links: ApplicationLinks;
  goBack: () => void;
  goNext: () => void;
}) {
  const [editing, setEditing] = useState(false);
  const hasLinks = Boolean(links.linkedin.trim() || links.portfolio.trim());

  return (
    <div className={styles.frame}>
      <div className={styles.appHeader}>
        <div className={styles.appLogo}>Mellow</div>
        <div className={styles.appHeaderRight}>
          <span>Final review · 1 of 1</span>
        </div>
      </div>

      <div className={styles.contextStrip}>
        <span className={styles.contextStripLabel}>Applying to</span>
        <span className={styles.contextStripTitle}>{REQUEST_TITLE}</span>
        <span className={styles.dot}>·</span>
        <span>{COMPANY}</span>
      </div>

      <div className={styles.confirmWrap}>
        <div className={styles.confirmIntro}>
          <h1 className={styles.confirmTitle}>Review what the client will see</h1>
          <p className={styles.confirmSub}>
            This is exactly what gets shared with the project leader. Nothing else — no internal
            score, no rate negotiation room.
          </p>
        </div>

        <div className={styles.previewCard}>
          <div className={styles.previewRow}>
            <div className={styles.previewLabel}>Profession</div>
            <div className={styles.previewValue}>{EXTRACTED.profession}</div>
          </div>
          <div className={styles.previewRow}>
            <div className={styles.previewLabel}>Level</div>
            <div className={styles.previewValue}>{EXTRACTED.level}</div>
          </div>
          <div className={styles.previewRow}>
            <div className={styles.previewLabel}>Top skills</div>
            <div className={styles.previewValue}>
              <div className={styles.pillRow}>
                {EXTRACTED.skills.map((s) => (
                  <span key={s} className={styles.pill}>
                    {s}
                  </span>
                ))}
              </div>
            </div>
          </div>
          <div className={styles.previewRow}>
            <div className={styles.previewLabel}>Location</div>
            <div className={styles.previewValue}>{EXTRACTED.location}</div>
          </div>
          <div className={styles.previewRow}>
            <div className={styles.previewLabel}>Languages</div>
            <div className={styles.previewValue}>
              <div className={styles.pillRow}>
                {EXTRACTED.languages.map((l) => (
                  <span key={l} className={styles.pill}>
                    {l}
                  </span>
                ))}
              </div>
            </div>
          </div>
          <div className={styles.previewRow}>
            <div className={styles.previewLabel}>
              Cover letter
              <button
                type="button"
                className={styles.previewEditLink}
                onClick={() => setEditing((v) => !v)}
              >
                {editing ? "Done" : "Edit"}
              </button>
            </div>
            <div className={`${styles.previewValue} ${styles.coverPreview}`}>
              {editing ? (
                <textarea
                  className={styles.coverTextarea}
                  value={cover}
                  onChange={(e) => setCover(e.target.value)}
                />
              ) : cover ? (
                cover
              ) : (
                <span className={styles.previewMuted}>No cover letter yet.</span>
              )}
            </div>
          </div>
          <div className={styles.previewRow}>
            <div className={styles.previewLabel}>Attachments</div>
            <div className={styles.previewValue}>
              {extras.length === 0 ? (
                <span className={styles.previewMuted}>None</span>
              ) : (
                <div className={styles.previewFiles}>
                  {extras.map((f) => (
                    <div key={f} className={styles.previewFileRow}>
                      <span className={styles.extraIcon} aria-hidden>
                        ▢
                      </span>
                      <span>{f}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
          <div className={styles.previewRow}>
            <div className={styles.previewLabel}>Links</div>
            <div className={styles.previewValue}>
              {hasLinks ? (
                <div className={styles.previewLinks}>
                  {links.linkedin.trim() ? (
                    <div>
                      <span className={styles.previewLinkLabel}>LinkedIn:</span>{" "}
                      <span>{links.linkedin}</span>
                    </div>
                  ) : null}
                  {links.portfolio.trim() ? (
                    <div>
                      <span className={styles.previewLinkLabel}>Portfolio:</span>{" "}
                      <span>{links.portfolio}</span>
                    </div>
                  ) : null}
                </div>
              ) : (
                <span className={styles.previewMuted}>None</span>
              )}
            </div>
          </div>
        </div>

        <p className={styles.confirmHidden}>
          Hidden from client: your expected rate, internal match score.
        </p>

        <div className={styles.confirmActions}>
          <button type="button" className={styles.secondaryBtn} onClick={goBack}>
            ← Edit my answers
          </button>
          <button type="button" className={styles.primaryBtn} onClick={goNext}>
            Submit application
          </button>
        </div>
      </div>
    </div>
  );
}

/* ============================================================
   5) RADAR — Project Details (Applied)
   Содержит post-submit success-баннер сверху (бывший шаг Success).
   ============================================================ */

function RadarAppliedStep({
  firstName,
  lastName,
}: {
  firstName: string;
  lastName: string;
}) {
  const [congratsOpen, setCongratsOpen] = useState(true);
  const initials =
    `${(firstName || "J").charAt(0)}${(lastName || "M").charAt(0)}`.toUpperCase();

  return (
    <div className={styles.radarRoot}>
      <nav className={styles.radarMenu} aria-label="Radar menu">
        <div className={styles.radarMenuLogo} aria-label="Mellow">
          W
        </div>
        <button type="button" className={styles.radarMenuIcon} aria-label="Discover">
          <CompassIcon />
        </button>
        <button
          type="button"
          className={`${styles.radarMenuIcon} ${styles.radarMenuIconActive}`}
          aria-label="Projects"
        >
          <SparkleIcon />
        </button>
        <button type="button" className={styles.radarMenuIcon} aria-label="Approved">
          <DoubleCheckIcon />
        </button>
        <button type="button" className={styles.radarMenuIcon} aria-label="Archive">
          <ArchiveIcon />
        </button>
      </nav>

      <main className={styles.radarBody}>
        <header className={styles.radarTopBar}>
          <div className={styles.radarTopLeft}>
            <button type="button" className={styles.radarBack}>
              ← Back to projects
            </button>
            <div className={styles.radarTitleRow}>
              <h1 className={styles.radarTitle}>{REQUEST_TITLE}</h1>
              <button type="button" className={styles.stageBadge}>
                Applied <span className={styles.stageBadgeCaret}>▾</span>
              </button>
            </div>
            <div className={styles.radarSubInfo}>
              <span>{COMPANY}</span>
              <span className={styles.dot}>·</span>
              <span>Scout by Mellow</span>
              <span className={styles.dot}>·</span>
              <a href="#landing">View original ↗</a>
            </div>
          </div>
          <div className={styles.radarTopRight}>
            <button
              type="button"
              className={styles.radarIconBtn}
              aria-label="Notifications"
            >
              <span className={styles.bellDot} />
              <BellIcon />
            </button>
            <button type="button" className={styles.radarWorkspaceBtn}>
              Project Radar <span className={styles.stageBadgeCaret}>▾</span>
            </button>
            <div className={styles.radarAvatar} aria-label="Account">
              {initials}
            </div>
          </div>
        </header>

        <div className={styles.radarContent}>
          <section className={styles.detailsCard}>
            <h2 className={styles.detailsTitle}>Details</h2>
            <p className={styles.detailsBody}>
              Studio M is looking for a Graphic Designer to revitalize their social media visuals
              and marketing materials. The role is ongoing, under 20 hrs/week, focused on brand
              identity work and campaign assets across channels.
            </p>
            <h3 className={styles.detailsSubTitle}>What you'll do</h3>
            <p className={styles.detailsBody}>
              You'll work directly with the marketing team, contributing to creative concepts,
              illustrations, and layouts. Strong portfolio in Figma, Photoshop, and Illustrator
              is required.
            </p>
            <h3 className={styles.detailsSubTitle}>Who you are</h3>
            <p className={styles.detailsBody}>
              A self-starter who can ship independently. You're comfortable owning a brief end to
              end and pushing back when something doesn't serve the brand.
            </p>
            <div className={styles.detailsMeta}>
              <span>Published 3 days ago</span>
              <span className={styles.dot}>·</span>
              <span>Applied a few seconds ago</span>
            </div>
          </section>

          <div className={styles.radarRightCol}>
            <aside className={styles.overviewCard}>
              <div className={styles.overviewHead}>
                <h3 className={styles.overviewTitle}>Overview</h3>
                <span className={styles.overviewScore}>✦ 87%</span>
              </div>
              <OverviewRow label="Role" value={EXTRACTED.profession} />
              <OverviewRow label="Experience" value="Middle" />
              <OverviewRow label="Languages" value="English, Spanish" />
              <OverviewRow label="Location" value={COMPANY_LOC} />
              <OverviewRow label="Budget" value="$25–35/hr" />
              <OverviewRow label="Project type" value="Ongoing" />
              <div className={styles.overviewActions}>
                <button type="button" className={styles.secondaryBtn} style={{ flex: 1 }}>
                  Move to In talks
                </button>
                <button
                  type="button"
                  className={styles.overviewKebab}
                  aria-label="More actions"
                >
                  ⋮
                </button>
              </div>
            </aside>

            <aside className={styles.funnelCard}>
              <h3 className={styles.overviewTitle}>Funnel stage</h3>
              <FunnelRow label="Interested" value="Apr 19, 2026" status="done" />
              <FunnelRow label="Applied" value="Current stage" status="current" />
              <FunnelRow label="In talks" status="empty" />
              <FunnelRow label="Deal settled" status="empty" />
              <FunnelRow label="Invoiced" status="empty" />
            </aside>
          </div>
        </div>

        {congratsOpen ? (
          <CongratsModal onClose={() => setCongratsOpen(false)} />
        ) : null}
      </main>
    </div>
  );
}

function OverviewRow({ label, value }: { label: string; value: string }) {
  return (
    <div className={styles.overviewRow}>
      <span className={styles.overviewLabel}>{label}</span>
      <span className={styles.overviewDots} aria-hidden />
      <span className={styles.overviewValue}>{value}</span>
    </div>
  );
}

function FunnelRow({
  label,
  value,
  status,
}: {
  label: string;
  value?: string;
  status: "done" | "current" | "empty";
}) {
  const pillClass = `${styles.funnelPill} ${
    status === "current"
      ? styles.funnelPillCurrent
      : status === "empty"
        ? styles.funnelPillEmpty
        : styles.funnelPillDone
  }`;

  return (
    <div className={styles.funnelRow}>
      <span
        className={`${styles.funnelLabel} ${status === "empty" ? styles.funnelLabelMuted : ""}`}
      >
        {label}
      </span>
      <span className={pillClass}>
        {status === "empty" ? (
          <span className={styles.funnelDash} aria-hidden>
            —
          </span>
        ) : (
          <>
            <span className={styles.funnelPillText}>{value}</span>
            {status === "done" ? (
              <span className={styles.funnelPillCheck} aria-hidden>
                <CheckIcon />
              </span>
            ) : null}
          </>
        )}
      </span>
    </div>
  );
}

/* ----------------- B/W inline icons (Radar) ----------------- */

function CompassIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <circle cx="12" cy="12" r="9" />
      <path d="M16.24 7.76l-2.83 6.36-6.36 2.83 2.83-6.36z" />
    </svg>
  );
}

function SparkleIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M12 3v18M3 12h18M5.6 5.6l12.8 12.8M18.4 5.6L5.6 18.4" />
    </svg>
  );
}

function DoubleCheckIcon() {
  return (
    <svg
      width="22"
      height="22"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M2 13l3.5 3.5L13 9" />
      <path d="M9 16l3.5 3.5L22 9" />
    </svg>
  );
}

function ArchiveIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <rect x="3" y="4" width="18" height="4.5" rx="1" />
      <path d="M5 8.5V19a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8.5" />
      <path d="M10 12.5h4" />
    </svg>
  );
}

function BellIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg
      width="12"
      height="12"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="3"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M5 13l4 4L19 7" />
    </svg>
  );
}

function CongratsModal({ onClose }: { onClose: () => void }) {
  return (
    <div className={styles.modalBackdrop} role="dialog" aria-modal="true">
      <div className={styles.modalCard}>
        <button
          type="button"
          className={styles.modalClose}
          onClick={onClose}
          aria-label="Close"
        >
          ×
        </button>
        <div className={styles.modalIcon} aria-hidden>
          ✓
        </div>
        <h2 className={styles.modalTitle}>Congrats! You applied!</h2>
        <p className={styles.modalText}>
          You applied for <strong>{REQUEST_TITLE}</strong>. You can track the status of your
          application in your Project Radar workspace.
        </p>
        <div className={styles.modalActions}>
          <button type="button" className={styles.primaryBtn} onClick={onClose}>
            Continue
          </button>
        </div>
      </div>
    </div>
  );
}

/* ============================================================
   Root
   ============================================================ */

export type ApplicationLinks = { linkedin: string; portfolio: string };

export function ScoutApplyFlowScreen() {
  const { step, setStep, idx, goNext, goBack } = useStep();
  const [cover, setCover] = useState("");
  const [extras, setExtras] = useState<string[]>([]);
  const [links, setLinks] = useState<ApplicationLinks>({ linkedin: "", portfolio: "" });
  const [firstName, setFirstName] = useState(SAMPLE_USER.firstName);
  const [lastName, setLastName] = useState(SAMPLE_USER.lastName);
  const [email, setEmail] = useState(SAMPLE_USER.email);

  const content = useMemo(() => {
    switch (step) {
      case "landing":
        return <LandingStep goNext={goNext} />;
      case "register":
        return (
          <RegistrationStep
            firstName={firstName}
            lastName={lastName}
            email={email}
            setFirstName={setFirstName}
            setLastName={setLastName}
            setEmail={setEmail}
            goNext={goNext}
          />
        );
      case "screening":
        return (
          <ScreeningStep
            firstName={firstName}
            lastName={lastName}
            email={email}
            cover={cover}
            setCover={setCover}
            extras={extras}
            setExtras={setExtras}
            links={links}
            setLinks={setLinks}
            goNext={goNext}
          />
        );
      case "confirm":
        return (
          <ConfirmStep
            cover={cover}
            setCover={setCover}
            extras={extras}
            links={links}
            goBack={goBack}
            goNext={goNext}
          />
        );
      case "radar":
        return <RadarAppliedStep firstName={firstName} lastName={lastName} />;
      default:
        return null;
    }
  }, [step, cover, extras, links, firstName, lastName, email, goNext, goBack]);

  return (
    <div className={styles.root}>
      <PrototypeBar step={step} idx={idx} goNext={goNext} goBack={goBack} jump={setStep} />
      <div className={styles.canvas}>{content}</div>
    </div>
  );
}
